% ----------
% CP model of the MultiProduct Vehicle 
% Routing Problem with ChangeOver Costs
%
% @author: Rosas B.
% @url: https://ifri-ai-classes.github.io/MPVRP-CC/
% @date: 06.2026
% ----------

include "alldifferent_except.mzn";
include "alldifferent_except_0.mzn";
include "among.mzn";
include "at_most.mzn";
include "cumulative.mzn";
include "gecode.mzn";
include "globals.mzn";
include "path.mzn";

% ----> parameters


% ----> functions


% ----> decisions variables


% ----> constraints


% ----> search